version: '3.8'

services:
  spring-boot:
    image: ghcr.io/${GITHUB_REPOSITORY:-your-username/your-repo}:latest
    container_name: spring-boot-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=aws
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME:-gamedb}
      - DB_USERNAME=${DB_USERNAME:-admin}
      - DB_PASSWORD=${DB_PASSWORD}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ./logs:/app/logs
